name: ci 
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: npm install -g staticrypt
      - run: ls -la ./docs/encrypted; ls -la ./; ls -la ./docs
      - run: find ./docs/encrypted/* -type f -name "*.html"
      - run: mkdocs gh-deploy --force
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      # - run: echo "./"; ls -la ./; echo "./encrypted/test"; ls -la ./encrypted/test; cat ./encrypted/test/index.html
      - run: find ./encrypted/* -type f -name "*.html" -exec staticrypt {} -d encrypted -p ${{ secrets.STATICRYPT_PASSWORD }} -r \;
      # - run: find ./encrypted/* -type f -name "*.html"
      # - run: cat ./encrypted/test/index.html
      - run: |
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push
